import React, { useState } from 'react';
import { Bell, AlertTriangle, Info, CheckCircle2, ShieldAlert } from 'lucide-react';
import { useSimulation } from '../context/SimulationContext';
import { TrafficAlert, AlertSeverity } from '../types/trajectra';

export const AlertsPage: React.FC = () => {
  const { alerts } = useSimulation();
  const [filterSeverity, setFilterSeverity] = useState<string>('ALL');

  const filteredAlerts = alerts.filter(a =>
    filterSeverity === 'ALL' || a.severity === filterSeverity
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#1b2a4a] pb-4">
        <div>
          <h2 className="text-2xl font-bold font-mono text-white tracking-wide flex items-center gap-2">
            <Bell className="w-6 h-6 text-cyan-400" />
            REAL-TIME TRAFFIC ALERTS & INCIDENT INCIDENTS ({alerts.length})
          </h2>
          <p className="text-xs text-slate-400 font-sans mt-0.5">
            Automated alerts generated by cross-camera ANPR, optical speed sensors, and congestion density metrics
          </p>
        </div>

        {/* Severity Filter Pills */}
        <div className="flex items-center space-x-2 text-xs font-mono">
          {(['ALL', 'CRITICAL', 'WARNING', 'INFO'] as const).map(sev => (
            <button
              key={sev}
              onClick={() => setFilterSeverity(sev)}
              className={`px-3 py-1.5 rounded-xl font-bold transition-all ${
                filterSeverity === sev
                  ? 'bg-cyan-500 text-black shadow-lg shadow-cyan-500/20'
                  : 'bg-[#0d1527] text-slate-400 hover:text-white border border-[#1b2a4a]'
              }`}
            >
              {sev}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Stream List */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => (
          <div
            key={alert.id}
            className={`p-5 rounded-2xl border shadow-xl space-y-2 transition-all ${
              alert.severity === 'CRITICAL'
                ? 'bg-rose-950/20 border-rose-500/40'
                : alert.severity === 'WARNING'
                ? 'bg-amber-950/20 border-amber-500/40'
                : 'bg-cyan-950/20 border-cyan-500/40'
            }`}
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <span
                  className={`px-2.5 py-0.5 rounded text-[10px] font-mono font-bold ${
                    alert.severity === 'CRITICAL'
                      ? 'bg-rose-500 text-black'
                      : alert.severity === 'WARNING'
                      ? 'bg-amber-500 text-black'
                      : 'bg-cyan-500 text-black'
                  }`}
                >
                  {alert.severity}
                </span>
                <h4 className="text-sm font-bold font-mono text-white">{alert.title}</h4>
              </div>
              <span className="text-xs font-mono text-slate-400">{alert.timestamp}</span>
            </div>

            <div className="text-xs text-slate-300 font-sans leading-relaxed">
              <strong>Location:</strong> {alert.location} — {alert.description}
            </div>

            {alert.actionRecommended && (
              <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 text-xs font-mono text-cyan-300 mt-2">
                <strong>RECOMMENDED CONTROL ROOM ACTION:</strong> {alert.actionRecommended}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
